
export const LOGIN_USER="LOGIN_USER";
export const REGISTER_USER="REGISTER_USER";
export const GET_AUTH_USER="GET_AUTH_USER";
export const LOGOUT="LOGOUT";
export const AUTH_ERROR="AUTH_ERROR";
export const SET_LOADING="SET_LOADING";
export const CLEAR_MSG='CLEAR_MSG';

//export const GET_USERS="GET_USERS" ;
export const GET_PRES_QUESTIONS="GET_PRES_QUESTIONS" ;
export const GET_LEGIS_QUESTIONS="GET_LEGIS_QUESTIONS" ;
export const GET_POLITICIANS="GET_POLITICIANS" ;
export const GET_PARTIES="GET_PARTIES" ;
export const GET_USERS="GET_USERS" ;
export const DELETE_USER="DELETE_USER" ;
export const VOTE_POLITICIAN="VOTE_POLITICIAN" ;
export const VOTE_PARTY="VOTE_PARTY" ;
export const USER_VOTED="USER_VOTED" ;
export const VOTED="VOTED" ;
export const LEGISVOTED="LEGISVOTED" ;

export const VOTE_ERROR="VOTE_ERROR";
export const ADMIN_ERROR="ADMIN_ERROR";
export const UPDATE_POLITICIAN="UPDATE_POLITICIAN";
export const UPDATE_PARTY="UPDATE_PARTY";
export const UPDATE_QUESTION="UPDATE_QUESTION";
